const formats={story:{w:1080,h:1920,label:'IG Story 1080×1920'},post45:{w:1080,h:1350,label:'IG Post 4:5 1080×1350'}};
let currentFormatKey='post45',artW=1080,artH=1350,pg;
const PANEL_W=340,PAD=14;
const BRUSH_PALETTE=['#0B0B0F','#E1F312','#7D3FCE','#0EC040','#DE08EE','#3ECBE8','#FF4D4D','#FF9F1C','#1E90FF'];
const BG_PALETTE=['#FFFFFF','#0B0B0F','#F5F5F7','#FFF2CC','#EAF7FF','#F6E9FF','#EFFFF0'];
const EMOJIS=['🐀','🐁','🧀','🕳️','🏠','📦','🍞','🥜','🗑️','🧱','🧦','🐾'];
let brushColorIndex=0,bgColorIndex=5,showGrid=true,eraserOn=false,isDrawing=false,viewScale=1;
let history=[],historyMax=25,emojiScale=1,popupFontSize=44,artTitle='RAT TOOL';
let popups=new Array(5).fill(null),draggingPopupId=-1,dragOffX=0,dragOffY=0;
let logo1=null,logo2=null,logo3=null,usedEmojiCells=new Set();
let titleInput,emojiSlider,textInputs=[],emojiButtons=[];
let btnExport,btnUndo,btnClear,btnGrid,btnEraser,btnFormat,btnZoomOut,btnZoomIn,btnZoomReset,btnPopupSmaller,btnPopupBigger;
let fileLogo1,fileLogo2,fileLogo3,lastWX=0,lastWY=0;
function panelX(){return artW+PAD} function panelW(){return PANEL_W-PAD*2}
function inArt(x,y){return x>=0&&x<artW&&y>=0&&y<artH}
function toWorld(x,y){const cx=artW/2,cy=artH/2;return{x:(x-cx)/viewScale+cx,y:(y-cy)/viewScale+cy}}
function safeAreaRect(){return currentFormatKey==='story'?{x:70,y:250,w:artW-140,h:artH-390}:{x:60,y:90,w:artW-120,h:artH-200}}
function centerProtectedRect(){const s=currentFormatKey==='story'?360:320;return{x:artW/2-s/2,y:artH/2-s/2,w:s,h:s}}
function rectsOverlap(a,b,p=0){return !(a.x+a.w+p<=b.x||b.x+b.w+p<=a.x||a.y+a.h+p<=b.y||b.y+b.h+p<=a.y)}
function estimatePopupSize(body,fs){const s=safeAreaRect();let w=constrain(280+body.length*2.8+fs*2.2,260,min(640,s.w));let lines=max(1,ceil(body.length/max(18,floor(w/(fs*.55)))));return{w,h:constrain(76+lines*fs*1.15,150,min(440,s.h))}}
function clampPopup(p){const s=safeAreaRect();p.x=constrain(p.x,s.x,s.x+s.w-p.w);p.y=constrain(p.y,s.y,s.y+s.h-p.h)}
function resolveCenter(p){const c=centerProtectedRect();if(!rectsOverlap(p,c))return;const opts=[{dx:-((p.x+p.w)-c.x),dy:0},{dx:(c.x+c.w)-p.x,dy:0},{dx:0,dy:-((p.y+p.h)-c.y)},{dx:0,dy:(c.y+c.h)-p.y}];opts.sort((a,b)=>(abs(a.dx)+abs(a.dy))-(abs(b.dx)+abs(b.dy)));p.x+=opts[0].dx;p.y+=opts[0].dy;clampPopup(p)}
function findPlacement(w,h){const s=safeAreaRect(),existing=popups.filter(Boolean),c=centerProtectedRect();let best={x:s.x,y:s.y,w,h},score=Infinity;for(let i=0;i<250;i++){const cand={x:random(s.x,s.x+s.w-w),y:random(s.y,s.y+s.h-h),w,h};let sc=rectsOverlap(cand,c)?9999:0;for(const r of existing)if(rectsOverlap(cand,r,14))sc++;if(sc<score){score=sc;best=cand;if(sc===0)break}}return best}
function setup(){setupForFormat(currentFormatKey);setupUI();pushHistory();syncPopups(true)}
function setupForFormat(k){currentFormatKey=k;artW=formats[k].w;artH=formats[k].h;createCanvas(artW+PANEL_W,artH);pixelDensity(1);noSmooth();const old=pg;pg=createGraphics(artW,artH);pg.pixelDensity(1);pg.noSmooth();pg.clear();if(old)pg.image(old,0,0,artW,artH);usedEmojiCells.clear();viewScale=1}
function setupUI(){btnExport=makeBtn('EXPORT PNG',exportNoUI);btnUndo=makeBtn('UNDO',undo);btnClear=makeBtn('CLEAR',clearAll);btnGrid=makeBtn('GRID: ON',()=>{showGrid=!showGrid;btnGrid.html(`GRID: ${showGrid?'ON':'OFF'}`)});btnEraser=makeBtn('ERASER: OFF',()=>{eraserOn=!eraserOn;btnEraser.html(`ERASER: ${eraserOn?'ON':'OFF'}`)});btnFormat=makeBtn('FORMAT: 4:5',toggleFormat);btnZoomOut=makeBtn('ZOOM -',()=>viewScale=constrain(viewScale-.1,.6,2.2));btnZoomIn=makeBtn('ZOOM +',()=>viewScale=constrain(viewScale+.1,.6,2.2));btnZoomReset=makeBtn('RESET 1:1',()=>viewScale=1);btnPopupSmaller=makeBtn('TEXT -',()=>setPopupFontSize(popupFontSize-4));btnPopupBigger=makeBtn('TEXT +',()=>setPopupFontSize(popupFontSize+4));titleInput=createInput(artTitle);styleInput(titleInput);titleInput.input(()=>artTitle=titleInput.value());emojiSlider=createSlider(.6,2.6,1,.05);emojiSlider.input(()=>emojiScale=emojiSlider.value());for(const d of['11.12.2015','rat notes…','','','']){const i=createInput(d);styleInput(i);i.input(()=>syncPopups(false));textInputs.push(i)}fileLogo1=createFileInput(f=>handleLogo(f,1));fileLogo2=createFileInput(f=>handleLogo(f,2));fileLogo3=createFileInput(f=>handleLogo(f,3));for(const e of EMOJIS){const b=makeEmojiBtn(e,()=>dropEmoji(e));emojiButtons.push(b)}}
function draw(){background(236);push();translate(artW/2,artH/2);scale(viewScale);translate(-artW/2,-artH/2);noStroke();fill(BG_PALETTE[bgColorIndex]);rect(0,0,artW,artH);drawArtTitle(this);image(pg,0,0);if(showGrid)drawGridOn(this);drawPopupsOn(this);drawLogosOn(this);noFill();stroke(0);strokeWeight(3);rect(0,0,artW,artH);pop();drawPanelBackground();layoutUI();drawSwatchesPanel();drawPanelText()}
function drawArtTitle(g){g.push();g.textFont('Helvetica, Arial, sans-serif');g.textSize(constrain(floor(artH*.05),28,64));g.textAlign(CENTER,TOP);g.fill(0);g.noStroke();g.text(artTitle,artW*.5,artH*.08);g.pop()}
function drawGridOn(g){g.push();g.stroke(0,28);for(let x=artW/4;x<artW;x+=artW/4)g.line(x,0,x,artH);for(let y=artH/4;y<artH;y+=artH/4)g.line(0,y,artW,y);g.pop()}
function layoutUI(){const x=panelX(),w=panelW(),gap=10,bw=(w-gap)/2,bh=40;let y=50;for(const row of[[btnExport,btnUndo],[btnClear,btnGrid],[btnEraser,btnFormat],[btnZoomOut,btnZoomIn]]){row[0].position(x,y).size(bw,bh);row[1].position(x+bw+gap,y).size(bw,bh);y+=bh+gap}btnZoomReset.position(x,y).size(w,bh);y+=52;titleInput.position(x,y).size(w,34);y+=44;emojiSlider.position(x,y).size(w,18);y+=30;btnPopupSmaller.position(x,y).size(bw,bh);btnPopupBigger.position(x+bw+gap,y).size(bw,bh);y+=52;for(const i of textInputs){i.position(x,y).size(w,34);y+=42}let ex=x,ey=y+8;for(const b of emojiButtons){if(ex+56>x+w){ex=x;ey+=54}b.position(ex,ey).size(56,44);ex+=66}y=ey+62;for(const f of[fileLogo1,fileLogo2,fileLogo3]){f.position(x,y).size(w,38);y+=48}}
function drawPanelBackground(){push();noStroke();fill(255);rect(artW,0,PANEL_W,artH);stroke(0,30);line(artW,0,artW,artH);pop()}
function drawPanelText(){push();fill(0);noStroke();textFont('Helvetica, Arial, sans-serif');textAlign(LEFT,TOP);textSize(16);text('ASAP / RAT TOOL',panelX(),14);textSize(11);fill(0,150);text(formats[currentFormatKey].label,panelX(),32);pop()}
function swatchRects(){return{x:panelX(),sw:26,gap:8,yBrush:artH-58,yBG:artH-104}}
function drawSwatchesPanel(){const {x,sw,gap,yBrush,yBG}=swatchRects();push();textSize(12);fill(0);noStroke();text('BACKGROUND',x,yBG-18);BG_PALETTE.forEach((c,i)=>{fill(c);stroke(0,40);rect(x+i*(sw+gap),yBG,sw,sw,8)});noStroke();fill(0);text('BRUSH',x,yBrush-18);BRUSH_PALETTE.forEach((c,i)=>{fill(c);stroke(0,40);rect(x+i*(sw+gap),yBrush,sw,sw,8)});pop()}
function handleSwatch(mx,my){if(mx<artW)return false;const {x,sw,gap,yBrush,yBG}=swatchRects();for(let i=0;i<BG_PALETTE.length;i++){let sx=x+i*(sw+gap);if(mx>=sx&&mx<=sx+sw&&my>=yBG&&my<=yBG+sw){bgColorIndex=i;return true}}for(let i=0;i<BRUSH_PALETTE.length;i++){let sx=x+i*(sw+gap);if(mx>=sx&&mx<=sx+sw&&my>=yBrush&&my<=yBrush+sw){brushColorIndex=i;return true}}return false}
function stampBrush(x,y,px,py,first){pg.push();pg.noStroke();const d=constrain(floor(artH*.02),12,42),steps=max(1,floor(dist(px,py,x,y)/max(6,d*.35)));for(let i=0;i<=steps;i++){const t=i/steps,ix=lerp(px,x,t),iy=lerp(py,y,t);if(eraserOn){pg.erase();pg.circle(ix,iy,d);pg.noErase()}else{pg.fill(BRUSH_PALETTE[brushColorIndex]);pg.circle(ix,iy,d)}}pg.pop();if(first)pushHistory()}
function randomCell(){const cols=4,rows=4,cw=artW/cols,ch=artH/rows,free=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const k=`${c},${r}`;if(!usedEmojiCells.has(k))free.push({c,r,k,cw,ch})}if(!free.length)return null;const p=random(free);return{...p,cx:p.c*p.cw+p.cw/2,cy:p.r*p.ch+p.ch/2}}
function dropEmoji(e){const c=randomCell();if(!c)return;const s=constrain(floor(c.cw*emojiScale),85,340);pg.push();pg.textAlign(CENTER,CENTER);pg.textSize(s);pg.text(e,c.cx,c.cy);pg.pop();usedEmojiCells.add(c.k);pushHistory()}
function syncPopups(){for(let i=0;i<5;i++){const body=(textInputs[i].value()||'').trim();if(!body){popups[i]=null;continue}const sz=estimatePopupSize(body,popupFontSize);if(!popups[i]){const q=findPlacement(sz.w,sz.h);popups[i]={id:i,x:q.x,y:q.y,w:sz.w,h:sz.h,body}}else{Object.assign(popups[i],{w:sz.w,h:sz.h,body});clampPopup(popups[i])}resolveCenter(popups[i])}}
function drawPopupsOn(g){for(const p of popups.filter(Boolean)){g.push();g.noStroke();g.fill(255,245);g.rect(p.x,p.y,p.w,p.h,16);g.fill(0,18);g.rect(p.x,p.y,p.w,34,16,16,0,0);g.fill(0);g.textSize(popupFontSize);g.textAlign(LEFT,TOP);g.text(p.body,p.x+16,p.y+44,p.w-32,p.h-54);g.pop()}}
function setPopupFontSize(n){popupFontSize=constrain(n,12,120);syncPopups(false)}
function popupAt(wx,wy){for(let i=popups.length-1;i>=0;i--){const p=popups[i];if(p&&wx>=p.x&&wx<=p.x+p.w&&wy>=p.y&&wy<=p.y+p.h)return p}return null}
function handleLogo(f,n){if(!f||f.type!=='image')return;loadImage(f.data,img=>{if(n===1)logo1=img;if(n===2)logo2=img;if(n===3)logo3=img})}
function drawLogosOn(g){const imgs=[logo1,logo2,logo3].filter(Boolean);let x=artW-18-imgs.length*132;for(const img of imgs){const d=120,cx=x+d/2,cy=artH-18-d/2;g.push();g.noStroke();g.fill(255);g.circle(cx,cy,d);const sc=min((d-20)/img.width,(d-20)/img.height);g.image(img,cx-img.width*sc/2,cy-img.height*sc/2,img.width*sc,img.height*sc);g.pop();x+=132}}
function mousePressed(){if(handleSwatch(mouseX,mouseY)||!inArt(mouseX,mouseY))return;const w=toWorld(mouseX,mouseY),p=popupAt(w.x,w.y);if(p){draggingPopupId=p.id;dragOffX=w.x-p.x;dragOffY=w.y-p.y;return}const prev=toWorld(pmouseX,pmouseY);isDrawing=true;lastWX=w.x;lastWY=w.y;stampBrush(w.x,w.y,prev.x,prev.y,true)}
function mouseDragged(){const w=toWorld(mouseX,mouseY);if(draggingPopupId!==-1){const p=popups.find(x=>x&&x.id===draggingPopupId);if(p){p.x=w.x-dragOffX;p.y=w.y-dragOffY;clampPopup(p);resolveCenter(p)}return}if(isDrawing&&inArt(mouseX,mouseY)){stampBrush(w.x,w.y,lastWX,lastWY,false);lastWX=w.x;lastWY=w.y}}
function mouseReleased(){draggingPopupId=-1;if(isDrawing){isDrawing=false;pushHistory()}}
function keyPressed(){if(key==='[')setPopupFontSize(popupFontSize-4);if(key===']')setPopupFontSize(popupFontSize+4)}
function clearAll(){pg.clear();usedEmojiCells.clear();textInputs.forEach(i=>i.value(''));syncPopups(false);pushHistory()}
function toggleFormat(){const n=currentFormatKey==='story'?'post45':'story';btnFormat.html(`FORMAT: ${n==='story'?'STORY':'4:5'}`);setupForFormat(n);syncPopups(true);pushHistory()}
function exportNoUI(){const out=createGraphics(artW,artH);out.background(BG_PALETTE[bgColorIndex]);drawArtTitle(out);out.image(pg,0,0);if(showGrid)drawGridOn(out);drawPopupsOn(out);drawLogosOn(out);saveCanvas(out,`rat-tool_${currentFormatKey}`,'png');out.remove()}
function pushHistory(){history.push(pg.get());if(history.length>historyMax)history.shift()}
function undo(){if(history.length<=1)return;history.pop();pg.clear();pg.image(history[history.length-1],0,0,artW,artH)}
function makeBtn(t,fn){const b=createButton(t);b.mousePressed(fn);b.style('font-family','Helvetica, Arial, sans-serif');b.style('border','1px solid rgba(0,0,0,.25)');b.style('border-radius','12px');b.style('background','rgba(0,0,0,.06)');b.style('cursor','pointer');return b}
function makeEmojiBtn(t,fn){const b=createButton(t);b.mousePressed(fn);b.style('font-size','22px');b.style('border-radius','999px');b.style('border','1px solid rgba(0,0,0,.25)');b.style('background','#fff');return b}
function styleInput(i){i.style('font-family','Helvetica, Arial, sans-serif');i.style('font-size','14px');i.style('padding','8px');i.style('border-radius','10px');i.style('border','1px solid rgba(0,0,0,.2)')}
